version: "3.3"

services:
  cooperativeit:
    image: php:7.2-apache
    container_name: cooperativeit
    volumes:
      - ${FILE_PATH}/website:/var/www/html/
      - ${FILE_PATH}/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
    restart: always